language: go

sudo: false

go:
  - 1.18.x

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
